version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    volumes:
      - .:/app
      # - bundle_install:/app/vendor/bundle
# volumes: 
#   bundle_install:
